sudo : required


before_install: 
	- gem install asciidoctor
	- gem install asciidoctor-pdf --pre

script:
	- asciidoctor-pdf yolo.adoc -o yolo.pdf
	- asciidoctor yolo.adoc -o yolo.html

after_success:
	- echo Done!
